# Generated by Django 5.0.1 on 2024-01-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainaddress', models.TextField(max_length=1000)),
                ('streetaddress', models.TextField(max_length=1000)),
                ('phonenumber', models.TextField(max_length=20)),
                ('openinghrs', models.TextField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
