# Generated by Django 5.0.1 on 2024-01-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ourpackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packagename', models.CharField(max_length=500)),
                ('packdis', models.CharField(max_length=500)),
                ('line1', models.TextField()),
                ('line2', models.TextField()),
                ('line3', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='contactus',
            name='mainaddress',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='openinghrs',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phonenumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='streetaddress',
            field=models.CharField(max_length=1000),
        ),
    ]
